package dev.civilization;
import net.minecraft.core.*;
import net.minecraft.gametest.framework.*;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.state.properties.*;
import net.minecraft.world.item.*;
import net.minecraft.world.entity.item.ItemEntity;
import net.minecraft.world.phys.AABB;
import net.neoforged.neoforge.gametest.*;
@GameTestHolder("civilization") @PrefixGameTestTemplate(false)
public final class WeatherGameTests {
 private static void harvestAsPlayer(GameTestHelper h,ServerLevel l,BlockPos p){var player=new net.neoforged.neoforge.common.util.FakePlayer(l,new com.mojang.authlib.GameProfile(java.util.UUID.randomUUID(),"weather-farmer"));player.setGameMode(net.minecraft.world.level.GameType.SURVIVAL);player.setPos(net.minecraft.world.phys.Vec3.atCenterOf(p.above()));h.assertTrue(player.gameMode.destroyBlock(p),"Manual harvest succeeds");}
 private static ServerLevel river(GameTestHelper h){return GeographyGameTests.region(h,"river");}
 private static SoilChunk.Soil plant(ServerLevel l,BlockPos p,net.minecraft.world.level.block.Block b){l.setChunkForced(p.getX()>>4,p.getZ()>>4,true);l.getChunkAt(p);for(var e:l.getEntitiesOfClass(ItemEntity.class,new AABB(p).inflate(4)))e.discard();l.setBlockAndUpdate(p,Blocks.AIR.defaultBlockState());l.setBlockAndUpdate(p.above(),Blocks.AIR.defaultBlockState());l.setBlockAndUpdate(p.below(),Blocks.FARMLAND.defaultBlockState());l.setBlockAndUpdate(p,b.defaultBlockState());l.setBlockAndUpdate(p.above(3),Blocks.GLOWSTONE.defaultBlockState());var s=SoilSystem.observe(l,p.below());s.target=7200;return s;}
 @GameTest(template="empty") public static void regionalRainPersistsAndDoesNotStack(GameTestHelper h){var l=h.getLevel();var p=new BlockPos(-2049,64,2048);var w=RegionalWeather.get(l);var n=p.east(512);h.assertTrue(RegionalWeather.key(-1,-1)==RegionalWeather.key(-512,-512)&&RegionalWeather.key(-513,-1)!=RegionalWeather.key(-512,-1),"Negative district boundaries");w.clear(l,p);w.clear(l,n);h.assertTrue(w.call(l,p),"First call starts rain");long end=w.district(l,RegionalWeather.key(p.getX(),p.getZ())).end;h.assertTrue(!w.call(l,p)&&end==w.district(l,RegionalWeather.key(p.getX(),p.getZ())).end,"Repeated call cannot extend rain");h.assertTrue(!w.district(l,RegionalWeather.key(n.getX(),n.getZ())).rain,"Neighbor unchanged");var copy=RegionalWeather.load(w.save(new net.minecraft.nbt.CompoundTag(),l.registryAccess()),l.registryAccess());h.assertTrue(copy.district(l,RegionalWeather.key(p.getX(),p.getZ())).end==end,"Schedule survives reload");h.assertTrue(RegionalWeather.waitTicks(.000001,12)<20&&RegionalWeather.waitTicks(.9999,12)>48*72000L,"No cooldown or maximum drought");h.succeed();}
 @GameTest(template="empty") public static void rainfallCoolsThenRecoversWithoutResettingOnReload(GameTestHelper h){
  var l=h.getLevel();var p=new BlockPos(1024,70,1024);var neighbor=p.east(512);var weather=new RegionalWeather();
  weather.clear(l,p);weather.clear(l,neighbor);weather.call(l,p);
  h.assertTrue(weather.coolingFor(l,p)==0&&weather.coolingFor(l,neighbor)==0,"Rain starts cooling without a temperature jump");
  weather.clock+=6000;
  double wet=weather.coolingFor(l,p);
  h.assertTrue(wet>.6&&wet<.7&&weather.coolingFor(l,neighbor)==0,"Only the rainy district cools over time");
  var restored=RegionalWeather.load(weather.save(new net.minecraft.nbt.CompoundTag(),l.registryAccess()),l.registryAccess());
  h.assertTrue(Math.abs(restored.coolingFor(l,p)-wet)<1e-9,"Cooling state survives reload");
  restored.clear(l,p);restored.clock+=48000;
  double after=restored.coolingFor(l,p);
  h.assertTrue(after>0&&after<wet*.4,"Cooling lingers after rain, then gradually recovers");h.succeed();
 }
 @GameTest(template="empty",timeoutTicks=200) public static void kilnNeedsAWeatherShelteredWorkFace(GameTestHelper h){
  var l=river(h);var p=new BlockPos(400,90,450);l.getChunk(p);
  var state=KilnContent.KILN.get().defaultBlockState().setValue(AbstractFurnaceBlock.FACING,Direction.NORTH);
  l.setBlockAndUpdate(p,Blocks.AIR.defaultBlockState());
  l.setBlockAndUpdate(p,state);
  for(var part:MachineStructure.parts(state))MachineStructure.placePart(l,p,Direction.NORTH,part);
  var kiln=(KilnBlockEntity)l.getBlockEntity(p);var face=p.north();var roof=face.above(3);
  l.setBlockAndUpdate(roof,Blocks.AIR.defaultBlockState());
  float oldRain=l.getRainLevel(1);l.setRainLevel(1);
  try{
   h.assertTrue(kiln.checkStructure().status()==MachineStructure.COMPLETE,"Kiln shell complete");
   h.assertTrue(MachineWeather.wetWorkFace(l,p,state),"Rain reaches the open firing face: rain="+l.isRainingAt(face)+", sky="+l.canSeeSky(face)+", height="+l.getHeightmapPos(net.minecraft.world.level.levelgen.Heightmap.Types.MOTION_BLOCKING,face).getY()+", biome="+l.getBiome(face).value().getPrecipitationAt(face));
   kiln.setItem(0,new ItemStack(Items.CLAY));kiln.setItem(1,KilnContent.MINERAL_COAL.toStack(2));
   h.assertTrue(!kiln.fire.strike(true)&&kiln.getItem(1).getCount()==2,"Wet fire cannot be ignited");
   l.setBlockAndUpdate(roof,Blocks.BRICKS.defaultBlockState());
   h.assertTrue(!MachineWeather.wetWorkFace(l,p,state),"A roof over the work face stops direct rain");
   for(long seed=0;;seed++){var random=net.minecraft.util.RandomSource.create(seed);random.nextFloat();if(random.nextInt(3)==0){l.random.setSeed(seed);break;}}
   h.assertTrue(kiln.fire.strike(true)&&kiln.fire.lit(),"Sheltered kiln lights during district rain");
   l.setBlockAndUpdate(roof,Blocks.AIR.defaultBlockState());
   for(int i=0;i<250;i++)KilnBlockEntity.tick(l,p,kiln.getBlockState(),kiln);
   h.assertTrue(kiln.getItem(0).getCount()==1&&kiln.getItem(2).isEmpty(),"Exposed kiln retains ingredients without completing work");
   l.setBlockAndUpdate(roof,Blocks.BRICKS.defaultBlockState());
   for(int i=0;i<210;i++)KilnBlockEntity.tick(l,p,kiln.getBlockState(),kiln);
   h.assertTrue(kiln.getItem(0).isEmpty()&&kiln.getItem(2).is(Items.BRICK),"Roofed kiln resumes and completes work with its existing fire");
  }finally{l.setRainLevel(oldRain);l.setBlockAndUpdate(roof,Blocks.AIR.defaultBlockState());}
  h.succeed();
 }
 @GameTest(template="empty") public static void allFarmlandSpeciesUseTwoHourWetCycle(GameTestHelper h){var l=river(h);var blocks=java.util.List.of(Blocks.WHEAT,Blocks.CARROTS,Blocks.POTATOES,Blocks.BEETROOTS,Blocks.TORCHFLOWER_CROP,Blocks.PITCHER_CROP);for(int i=0;i<blocks.size();i++){var p=new BlockPos(256+i*16,64,256);var s=plant(l,p,blocks.get(i));s.water=7200;}
  h.runAfterDelay(5,()->{for(int i=0;i<blocks.size();i++){var p=new BlockPos(256+i*16,64,256);SoilSystem.advance(l,l.getChunkAt(p),3600);h.assertTrue(!SoilSystem.mature(l.getBlockState(p)),"Not mature at one wet hour: "+blocks.get(i));SoilSystem.advance(l,l.getChunkAt(p),3600);h.assertTrue(SoilSystem.mature(l.getBlockState(p)),"Mature at two wet hours: "+blocks.get(i));}h.succeed();});}
 @GameTest(template="empty") public static void baselineGrowthAndMoistureSave(GameTestHelper h){var l=river(h);var p=new BlockPos(256,64,304);var s=plant(l,p,Blocks.WHEAT);h.runAfterDelay(5,()->{SoilSystem.advance(l,l.getChunkAt(p),7200);h.assertTrue(!SoilSystem.mature(l.getBlockState(p)),"Two dry hours incomplete");SoilSystem.advance(l,l.getChunkAt(p),7200);h.assertTrue(SoilSystem.mature(l.getBlockState(p)),"Four dry hours mature");s.water=1200;var copy=new SoilChunk();copy.deserializeNBT(l.registryAccess(),l.getChunkAt(p).getData(SoilChunk.TYPE).serializeNBT(l.registryAccess()));h.assertTrue(copy.soils.get(p.below().asLong()).water==1200,"Water persists");l.destroyBlock(p,false);l.setBlockAndUpdate(p,Blocks.WHEAT.defaultBlockState());h.assertTrue(SoilSystem.observe(l,p.below()).water==1200,"Replant preserves water");h.succeed();});}
 @GameTest(template="empty") public static void fertilizerCarrotsConservePlantingAndYield(GameTestHelper h){var l=river(h);var p=new BlockPos(256,64,352);var s=plant(l,p,Blocks.CARROTS);h.assertTrue(SoilSystem.fertilize(l,p)&&!SoilSystem.fertilize(l,p),"One fertilizer dose per cycle");s.water=7200;h.startSequence().thenWaitUntil(()->h.assertTrue(l.isPositionEntityTicking(p),"Waiting for fixture entities")).thenExecute(()->{for(var e:l.getEntitiesOfClass(ItemEntity.class,new AABB(p).inflate(4)))e.discard();SoilSystem.advance(l,l.getChunkAt(p),7200);harvestAsPlayer(h,l,p);int count=l.getEntitiesOfClass(ItemEntity.class,new AABB(p).inflate(2)).stream().filter(e->e.getItem().is(Items.CARROT)).mapToInt(e->e.getItem().getCount()).sum();h.assertTrue(count==10,"One planting carrot plus nine produce: got "+count);h.assertTrue(!SoilSystem.observe(l,p.below()).fertilized,"Harvest clears dose");}).thenSucceed();}
 @GameTest(template="empty") public static void fruitRepeatCycleAndYield(GameTestHelper h){var l=river(h);var p=new BlockPos(256,64,400);var s=plant(l,p,Blocks.PUMPKIN_STEM);for(var d:Direction.Plane.HORIZONTAL){l.setBlockAndUpdate(p.relative(d),Blocks.AIR.defaultBlockState());l.setBlockAndUpdate(p.relative(d).below(),Blocks.DIRT.defaultBlockState());}s.water=7200;SoilSystem.fertilize(l,p);h.startSequence().thenWaitUntil(()->h.assertTrue(l.isPositionEntityTicking(p),"Waiting for fixture entities")).thenExecute(()->{for(var e:l.getEntitiesOfClass(ItemEntity.class,new AABB(p).inflate(4)))e.discard();SoilSystem.advance(l,l.getChunkAt(p),7200);h.assertTrue(l.getBlockState(p).is(Blocks.ATTACHED_PUMPKIN_STEM),"First fruit in two hours");var fruit=p.relative(l.getBlockState(p).getValue(HorizontalDirectionalBlock.FACING));harvestAsPlayer(h,l,fruit);int count=l.getEntitiesOfClass(ItemEntity.class,new AABB(p).inflate(3)).stream().filter(e->e.getItem().is(Items.PUMPKIN)).mapToInt(e->e.getItem().getCount()).sum();h.assertTrue(count==3&&!s.fertilized,"Fertilized fruit uses one dose and yields three: got "+count+", dose="+s.fertilized);l.setBlockAndUpdate(fruit,Blocks.PUMPKIN.defaultBlockState());harvestAsPlayer(h,l,fruit);int total=l.getEntitiesOfClass(ItemEntity.class,new AABB(p).inflate(3)).stream().filter(e->e.getItem().is(Items.PUMPKIN)).mapToInt(e->e.getItem().getCount()).sum();h.assertTrue(total==4,"Replaced fruit cannot reuse fertilizer yield");s.water=7200;s.target=7200;SoilSystem.advance(l,l.getChunkAt(p),3600);h.assertTrue(l.getBlockState(p).is(Blocks.PUMPKIN_STEM),"No fast repeat fruit");SoilSystem.advance(l,l.getChunkAt(p),3600);h.assertTrue(l.getBlockState(p).is(Blocks.ATTACHED_PUMPKIN_STEM),"Repeat fruit completes its own cycle");}).thenSucceed();}
 @GameTest(template="empty") public static void rainChargesSoilAndRoofBlocksIt(GameTestHelper h){var l=river(h);var p=new BlockPos(384,64,448);var s=plant(l,p,Blocks.WHEAT);l.setBlockAndUpdate(p.above(2),Blocks.AIR.defaultBlockState());l.setBlockAndUpdate(p.above(3),Blocks.AIR.defaultBlockState());h.runAfterDelay(5,()->{float old=l.getRainLevel(1);l.setRainLevel(1);try{h.assertTrue(l.isRainingAt(p),"Open field receives rain");SoilSystem.advance(l,l.getChunkAt(p),1800);h.assertTrue(s.water==7200,"Thirty minutes charges two hours");SoilSystem.advance(l,l.getChunkAt(p),1800);h.assertTrue(s.water==7200,"Reserve is capped");l.setBlockAndUpdate(p.above(2),Blocks.STONE.defaultBlockState());SoilSystem.advance(l,l.getChunkAt(p),60);h.assertTrue(s.water==7140,"Roof blocks recharge and soil dries");l.setRainLevel(0);SoilSystem.advance(l,l.getChunkAt(p),7140);h.assertTrue(s.water==0,"Reserve returns to river baseline");}finally{l.setRainLevel(old);}h.succeed();});}
 @GameTest(template="empty") public static void upperPitcherHarvestDropsOnce(GameTestHelper h){var l=river(h);var p=new BlockPos(416,64,448);var s=plant(l,p,Blocks.PITCHER_CROP);s.water=7200;SoilSystem.fertilize(l,p);h.startSequence().thenWaitUntil(()->h.assertTrue(l.isPositionEntityTicking(p),"Waiting for the fixture entity chunk")).thenExecute(()->{for(var e:l.getEntitiesOfClass(ItemEntity.class,new AABB(p).inflate(4)))e.discard();SoilSystem.advance(l,l.getChunkAt(p),7200);h.assertTrue(SoilSystem.mature(l.getBlockState(p.above())),"Mature upper before break: "+l.getBlockState(p.above())+", lower="+l.getBlockState(p)+", work="+s.work+", target="+s.target+", harvested="+s.harvested);harvestAsPlayer(h,l,p.above());int count=l.getEntitiesOfClass(ItemEntity.class,new AABB(p).inflate(4)).stream().filter(e->e.getItem().is(Items.PITCHER_PLANT)).mapToInt(e->e.getItem().getCount()).sum();h.assertTrue(count==3,"Breaking upper half yields one fertilized harvest: "+count+", entity ticking="+l.isPositionEntityTicking(p));for(var e:l.getEntitiesOfClass(ItemEntity.class,new AABB(p).inflate(4)))e.discard();var again=plant(l,p,Blocks.PITCHER_CROP);again.water=7200;SoilSystem.fertilize(l,p);SoilSystem.advance(l,l.getChunkAt(p),7200);harvestAsPlayer(h,l,p);int lower=l.getEntitiesOfClass(ItemEntity.class,new AABB(p).inflate(4)).stream().filter(e->e.getItem().is(Items.PITCHER_PLANT)).mapToInt(e->e.getItem().getCount()).sum();h.assertTrue(lower==3,"Lower-half harvest also drops exactly three: "+lower);}).thenSucceed();}

 @GameTest(template="empty") public static void melonUsesSameFullCycle(GameTestHelper h){var l=river(h);var p=new BlockPos(464,64,400);var s=plant(l,p,Blocks.MELON_STEM);for(var d:Direction.Plane.HORIZONTAL){l.setBlockAndUpdate(p.relative(d),Blocks.AIR.defaultBlockState());l.setBlockAndUpdate(p.relative(d).below(),Blocks.DIRT.defaultBlockState());}s.water=7200;SoilSystem.fertilize(l,p);h.startSequence().thenWaitUntil(()->h.assertTrue(l.isPositionEntityTicking(p),"Waiting for fixture entities")).thenExecute(()->{for(var e:l.getEntitiesOfClass(ItemEntity.class,new AABB(p).inflate(4)))e.discard();SoilSystem.advance(l,l.getChunkAt(p),3600);h.assertTrue(!l.getBlockState(p).is(Blocks.ATTACHED_MELON_STEM),"No early melon");SoilSystem.advance(l,l.getChunkAt(p),3600);h.assertTrue(l.getBlockState(p).is(Blocks.ATTACHED_MELON_STEM),"Melon first fruit in two wet hours");var fruit=p.relative(l.getBlockState(p).getValue(HorizontalDirectionalBlock.FACING));l.destroyBlock(fruit,true);int count=l.getEntitiesOfClass(ItemEntity.class,new AABB(p).inflate(3)).stream().filter(e->e.getItem().is(Items.MELON_SLICE)).mapToInt(e->e.getItem().getCount()).sum();h.assertTrue(count==9,"Fertilized melon gives nine slices");}).thenSucceed();}

}
