org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
neo_version=21.1.250
mod_id=civilization
mod_name=Civilization
mod_version=0.34.29-dev
jei_version=19.54.0.427
geckolib_version=4.9.3
mod_group_id=dev.civilization
